server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/microservice
    username: postgres
    password: comfy@1234
    driver-class-name: org.postgresql.Driver
  application:
    name: HOTEL-SERVICE
  jpa:
    hibernate:
      ddl-auto: update  # Use 'validate' for production to ensure the schema is up to date
    show-sql: true  # Show SQL queries in the logs
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  config:
    import: optional:configserver:http://localhost:8085
#eureka:
#  instance:
#    prefer-ip-address: true
#  client:
#    fetch-registry: true
#    register-with-eureka: true
#    service-url:
#      defaultZone: http://localhost:8761/eureka	