eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false #this service wouldn't get self registered
    fetch-registry: false #this service wouldn't be able to access the registry
server:
  port: 8761